"use client";

import { useState } from "react";
import { Mail, MapPin, MessageCircle } from "lucide-react";
import toast from "react-hot-toast";
import { apiFetch } from "@/lib/api";

export default function ContactPage() {
  const [form, setForm] = useState({ name: "", email: "", subject: "", message: "" });
  const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); try { await apiFetch("/content/contact", { method: "POST", body: JSON.stringify(form) }); setForm({ name: "", email: "", subject: "", message: "" }); toast.success("Message received"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not send message"); } finally { setLoading(false); } };
  return <div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="font-bold uppercase tracking-widest text-teal-700">Contact</p><h1 className="mt-3 text-5xl font-black">Tell us what needs attention.</h1><p className="mt-6 text-lg leading-8 text-slate-600">Report inaccurate listing details, request help with the platform, or share feedback about an AI workflow.</p><div className="mt-10 grid gap-4"><div className="flex gap-4 rounded-2xl bg-white p-5"><Mail className="text-teal-600" /><div><p className="font-black">Email</p><p className="text-sm text-slate-600">Use the secure form on this page</p></div></div><div className="flex gap-4 rounded-2xl bg-white p-5"><MessageCircle className="text-teal-600" /><div><p className="font-black">Support scope</p><p className="text-sm text-slate-600">Technical issues, data corrections, and responsible-AI feedback</p></div></div><div className="flex gap-4 rounded-2xl bg-white p-5"><MapPin className="text-teal-600" /><div><p className="font-black">Operation</p><p className="text-sm text-slate-600">Remote-first demonstration platform</p></div></div></div></div><form onSubmit={submit} className="grid gap-5 rounded-[2rem] border bg-white p-6 shadow-xl sm:p-9"><h2 className="text-2xl font-black">Send a message</h2><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-black">Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="h-12 rounded-xl border border-slate-300 px-4 font-normal" /></label><label className="grid gap-2 text-sm font-black">Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="h-12 rounded-xl border border-slate-300 px-4 font-normal" /></label></div><label className="grid gap-2 text-sm font-black">Subject<input required value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} className="h-12 rounded-xl border border-slate-300 px-4 font-normal" /></label><label className="grid gap-2 text-sm font-black">Message<textarea required minLength={20} rows={7} value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} className="rounded-xl border border-slate-300 px-4 py-3 font-normal" /></label><button disabled={loading} className="h-12 rounded-xl bg-slate-950 font-black text-white">{loading ? "Sending…" : "Send message"}</button></form></div>;
}
